
export const INVALIDATE_SUBREDDIT = 'INVALIDATE_SUBREDDIT'
export const RECEIVE_POSTS = 'RECEIVE_POSTS'
export const REQUEST_POSTS = 'REQUEST_POSTS'
export const SELECT_SUBREDDIT = 'SELECT_SUBREDDIT'
export const SLICE_POSTS = 'SLICE_POSTS'
